name: Generate static route list for Bird

on:
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate static route list
        run: |
          python main.py --region CN MO HK TW JP KR SG

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "route_list.conf"
