name: Generate static route list for Bird

on:
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYYMMDD

      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
          YEAR: "${{ steps.current-time.outputs.year }}"
          DAY: "${{ steps.current-time.outputs.day }}"
        run: echo $TIME $R_TIME $F_TIME $YEAR $DAY

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate static route list
        run: |
          echo ${{ steps.date.outputs.date }}
          python main.py --region CN MO HK TW JP KR SG --next eth0

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "route_list.conf"
          tag: nightly-${{ steps.current-time.outputs.formattedTime }}
